/**
 * Slack Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace SlackAPI
{

/*
 * OpenAPIApiChatPostMessagePostRequest
 *
 * 
 */
class SLACKOPENAPI_API OpenAPIApiChatPostMessagePostRequest : public Model
{
public:
    virtual ~OpenAPIApiChatPostMessagePostRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FString Channel;
	TOptional<FString> Text;
	TOptional<TArray<TSharedPtr<FJsonObject>>> Attachments;
	TOptional<TArray<TSharedPtr<FJsonObject>>> Blocks;
	TOptional<FString> ThreadTs;
};

}
