/**
 * Slack Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIChatApi.h"

#include "OpenAPIApiChatPostMessagePost200Response.h"
#include "OpenAPIApiChatPostMessagePostRequest.h"

namespace SlackAPI
{

/* 

*/
class SLACKOPENAPI_API OpenAPIChatApi::ApiChatPostMessagePostRequest : public Request
{
public:
    virtual ~ApiChatPostMessagePostRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	TOptional<OpenAPIApiChatPostMessagePostRequest> OpenAPIApiChatPostMessagePostRequest;
};

class SLACKOPENAPI_API OpenAPIChatApi::ApiChatPostMessagePostResponse : public Response
{
public:
    virtual ~ApiChatPostMessagePostResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIApiChatPostMessagePost200Response Content;
};

}
