/**
 * Slack Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIFileUploadApi.h"

#include "OpenAPIApiFilesUploadPost200Response.h"

namespace SlackAPI
{

/* 

*/
class SLACKOPENAPI_API OpenAPIFileUploadApi::ApiFilesUploadPostRequest : public Request
{
public:
    virtual ~ApiFilesUploadPostRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Content;
	TOptional<FString> Channels;
	TOptional<FString> InitialComment;
	TOptional<FString> ThreadTs;
	TOptional<FString> Title;
	TOptional<FString> Filename;
};

class SLACKOPENAPI_API OpenAPIFileUploadApi::ApiFilesUploadPostResponse : public Response
{
public:
    virtual ~ApiFilesUploadPostResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIApiFilesUploadPost200Response Content;
};

}
