/**
 * Slack Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIApiChatPostMessagePostRequest.h"

#include "SlackOpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace SlackAPI
{

void OpenAPIApiChatPostMessagePostRequest::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("channel")); WriteJsonValue(Writer, Channel);
	if (Text.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("text")); WriteJsonValue(Writer, Text.GetValue());
	}
	if (Attachments.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("attachments")); WriteJsonValue(Writer, Attachments.GetValue());
	}
	if (Blocks.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("blocks")); WriteJsonValue(Writer, Blocks.GetValue());
	}
	if (ThreadTs.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("thread_ts")); WriteJsonValue(Writer, ThreadTs.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIApiChatPostMessagePostRequest::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("channel"), Channel);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("text"), Text);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("attachments"), Attachments);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("blocks"), Blocks);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("thread_ts"), ThreadTs);

	return ParseSuccess;
}

}
