/**
 * Slack Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "SlackOpenAPIModule.h"

IMPLEMENT_MODULE(SlackOpenAPIModule, SlackOpenAPI);
DEFINE_LOG_CATEGORY(LogSlackOpenAPI);

void SlackOpenAPIModule::StartupModule()
{
}

void SlackOpenAPIModule::ShutdownModule()
{
}
